title: 咖喱没有土豆
description: 开心的时候写一下，没事的时候写一下，怕忘记的时候写一下
author: Millim
about: Level 0的开发者
# baseurl: "/"
url: "http://localhost:4000"
encoding: "utf-8"
allowsearch: false
enableTags: true
tagarray: []
paginate: 10
per_page: 1
paginate_path: "/page:num/"
permalink: /:categories/
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
version: 1.0.0
