default: 
  title: Millim学习记录
  description: 一切乱七八糟的东西
  author: Millim
  about: Level 0的开发者
  # baseurl: "/"
  url: "http://localhost:4000"
  encoding: "utf-8"
  allowsearch: false
  enableTags: true
  tagarray: []
  paginate: 10
  per_page: 10
  paginate_path: "/page:num/"
  markdown: kramdown
  plugins: [jekyll-paginate, jekyll-gist]
production:
  destination: ./docs
